#!/usr/bin/env bash
# Write the deploy-time image override file (Task 24 / M11 Phase 3).
#
# The checked-in compose files use ``build:`` for local/CI use. Deploys
# need immutable GHCR image tags, so the pipeline generates a small
# override that adds ``image:`` to every first-party service. The override
# is transient (gitignored) and never contains credentials.
#
# Usage:
#   IMAGE_REPO=ghcr.io/<owner>/<repo> IMAGE_TAG=<sha> \
#     bash tools/deploy/write-image-override.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

: "${IMAGE_REPO:?IMAGE_REPO required (e.g. ghcr.io/owner/repo)}"
: "${IMAGE_TAG:?IMAGE_TAG required (immutable commit sha tag)}"

OUT="infra/docker/compose.images.yml"

cat > "$OUT" <<EOF
# Transient deploy-time override generated by tools/deploy/write-image-override.sh.
# Pins every first-party service to an immutable GHCR image tag.
# NOTE: no ``name:`` key here — the base compose files already set the
# project name (prod/staging); an override name would silently switch the
# running stack's project identity.
services:
  api:
    image: ${IMAGE_REPO}/api:${IMAGE_TAG}
  aios-bridge:
    image: ${IMAGE_REPO}/aios-bridge:${IMAGE_TAG}
  content-service:
    image: ${IMAGE_REPO}/content-service:${IMAGE_TAG}
  affiliate-service:
    image: ${IMAGE_REPO}/affiliate-service:${IMAGE_TAG}
  pinterest-service:
    image: ${IMAGE_REPO}/pinterest-service:${IMAGE_TAG}
  seo-service:
    image: ${IMAGE_REPO}/seo-service:${IMAGE_TAG}
  analytics-service:
    image: ${IMAGE_REPO}/analytics-service:${IMAGE_TAG}
  admin-service:
    image: ${IMAGE_REPO}/admin-service:${IMAGE_TAG}
  automation-service:
    image: ${IMAGE_REPO}/automation-service:${IMAGE_TAG}
  automation-worker:
    image: ${IMAGE_REPO}/automation-service:${IMAGE_TAG}
  automation-beat:
    image: ${IMAGE_REPO}/automation-service:${IMAGE_TAG}
EOF

echo "wrote ${OUT}"
