import { createApiClient } from "@/lib/api-client";

export const revalidate = 3600;

const GROUP_RE = /^(articles|categories|tags|products|landing|collections)$/;
const SHARD_RE = /^[1-9][0-9]*$/;

/**
 * /sitemaps/{group}-index.xml and /sitemaps/{group}-{n}.xml (M7 §4):
 * proxies the shard/index XML generated by seo-service. Only whitelisted
 * group names and numeric shards are accepted — private or malformed paths
 * never reach the SEO service.
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ filename: string }> },
) {
  const { filename } = await params;
  const match = /^([a-z]+)-(index|[1-9][0-9]*)\.xml$/.exec(filename);
  if (!match) return new Response("Not Found", { status: 404 });
  const [, group, shard] = match;
  if (!GROUP_RE.test(group)) return new Response("Not Found", { status: 404 });
  if (shard !== "index" && !SHARD_RE.test(shard)) {
    return new Response("Not Found", { status: 404 });
  }
  const xml = await createApiClient().seo.getSitemap(filename);
  if (!xml) return new Response("Not Found", { status: 404 });
  return new Response(xml, {
    headers: { "content-type": "application/xml; charset=utf-8" },
  });
}
